name: Createments
main: zedly.createments.Createments
version: 3.14.159.26535.8
api-version: 1.14
commands:
  cr:
    description: 
    usage: /cr

permissions:
  createments.apocalypse:
    description: Starts/Stops the apocalypse
    default: false
  createments.arrow.info:
    description: Use of elemental arrow information
    default: false
  createments.arrow.create:
    description: Use of arrow create command
    default: false
  createments.arrow.use:
    description: Use of elemental arrows
    default: false
  createments.aura:
    description: Spawns an aura around the player
    default: false
  createments.emoticons:
    description: Use of emoticons in chat
    default: true
  createments.fusrodah:
    description: Blasts mobs and items away from the user.
    default: false
  createments.paragrapher:
    description: Creates paragraphers
    default: false
  createments.rainboom:
    description: Creates a rainbow trail of fireworks for the flying player
    default: false
  createments.rainbow:
    description: Makes the player's text colorful
    default: false
  createments.reload:
    description: Reloads plugin
    default: false
  createments.thebox:
    description: THE BOX
    default: true
  
  createments.*:
    children:
        createments.apocalypse: true
        createments.aura: true
        createments.emoticons: true
        createments.fusrodah: true
        createments.rainboom: true
        createments.rainbow: true
        createments.paragrapher: true
        createments.arrow.info: true
        createments.arrow.create: true
        createments.arrow.use: true
        createments.thebox: true